import "~/styles/globals.css";
import "@mantine/core/styles.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import {
  ColorSchemeScript,
  type MantineColorScheme,
  MantineProvider,
} from "@mantine/core";
import { cssVariablesResolver, themeOverride } from "~/theme";
import { ColorSchemeToggle } from "~/components/ColorSchemeToggle";
import {} from "@mantine/hooks";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const DEFAULT_COLOR_SCHEME: MantineColorScheme = "auto";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme={DEFAULT_COLOR_SCHEME} />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <MantineProvider
          defaultColorScheme={DEFAULT_COLOR_SCHEME}
          theme={themeOverride}
          cssVariablesResolver={cssVariablesResolver}
        >
          <TRPCReactProvider headers={headers()}>
            <ColorSchemeToggle className="absolute right-man_sm top-man_sm" />
            {children}
          </TRPCReactProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
